# Generated by Django 5.0.7 on 2024-07-23 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigproject', '0002_alter_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orientation_lesson_1_practice', models.BooleanField(default=False)),
                ('orientation_lesson_1_quiz', models.BooleanField(default=False)),
                ('orientation_lesson_2', models.BooleanField(default=False)),
                ('orientation_lesson_2_quiz', models.BooleanField(default=False)),
                ('orientation_lesson_3', models.BooleanField(default=False)),
                ('orientation_lesson_3_practice', models.BooleanField(default=False)),
                ('orientation_lesson_3_quiz', models.BooleanField(default=False)),
                ('analyzing_behavior_lesson_1', models.BooleanField(default=False)),
                ('analyzing_behavior_lesson_1_practice', models.BooleanField(default=False)),
                ('analyzing_behavior_lesson_1_quiz', models.BooleanField(default=False)),
                ('analyzing_behavior_lesson_2', models.BooleanField(default=False)),
                ('analyzing_behavior_lesson_2_practice', models.BooleanField(default=False)),
                ('analyzing_behavior_lesson_2_quiz', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
