# Generated by Django 5.0.7 on 2024-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigproject', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_mindfulness_lesson_1',
            field=models.BooleanField(default=False),
        ),
    ]
